objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HelloWorldTestClass.cls
@isTest
private class HelloWorldTestClass {
    /*static testMethod void validateHelloWorld(){
        Book__c book=new Book__c(Name='2 states',Price__c=100);
        System.debug('The price of the book before insertion'+book);
        insert book;
        book=[select Price__c from book__c where Id=:book.Id];
        System.debug('The price if the book after insertion'+book);
        System.assertEquals(90, book.Price__c);
    }*/
}