objects/players__c.object
<CustomObject>
    <fields>
        <fullName>teamrelation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>team</label>
        <referenceTo>team__c</referenceTo>
        <relationshipLabel>players</relationshipLabel>
        <relationshipName>players</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>player</label>
    <nameField>
        <label>players Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/team__c.object
<CustomObject>
    <fields>
        <fullName>numberofplayers__c</fullName>
        <label>numberofplayers</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>team</label>
    <nameField>
        <label>team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TeamPlayers.cls
public  class TeamPlayers {
     
    public static void fetching(Set<team__c> parentids){
        list<team__c> updatedcompanies=new list<team__c>();
        list<team__c> listofCompanies=new list<team__c>();
    listofCompanies=[select id,(select id from players__r) from team__c where id in:parentids];
       for( team__c t:listofCompanies)
       {
           
           t.numberofplayers__c=t.players__r.size();
           System.debug(t);
             
       }
        if(updatedcompanies.size()>0)
      update updatedcompanies;
    
        //Map<ID, Account> m = new Map<ID, Account>([SELECT Id, Name FROM Account LIMIT 14]);
// After populating the map, iterate through the map entries
//for (ID idKey : m.keyset()) {
  //  Account a = m.get(idKey);
   // System.debug(a);
//}

        
       }
}